<<<<<<< HEAD
# Generated by Django 5.1 on 2024-10-17 03:44
=======
# Generated by Django 5.1 on 2024-11-11 17:03
>>>>>>> 4c62fdb67493e2a621c685c3bb28689a2ab65cbe

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ophthalmologist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('result_analysis', models.TextField(blank=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('apparatus', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=50, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophthalmologist.patient')),
            ],
        ),
    ]
