# Generated by Django 5.0.7 on 2024-08-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('result_analysis', models.TextField(blank=True)),
                ('is_analyzed', models.BooleanField(default=False)),
            ],
        ),
    ]
