# Generated by Django 5.1 on 2024-10-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediflowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediflowApp.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
