# Generated by Django 5.1 on 2024-08-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediflowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
