# Generated by Django 5.1 on 2024-09-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediflowApp', '0002_alter_patient_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ophtalmologist',
            new_name='Ophthalmologist',
        ),
        migrations.RenameField(
            model_name='ophthalmologist',
            old_name='title',
            new_name='specialty',
        ),
    ]
