# Generated by Django 5.1 on 2024-09-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediflowApp', '0003_rename_ophtalmologist_ophthalmologist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ophthalmologist',
            name='address',
        ),
    ]
