# Generated by Django 5.1 on 2024-08-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediflowApp', '0003_remove_exam_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ophtalmologist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('medical_license', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
